### ISSUE TITLE
React boilerplate

### ISSUE THREAD

**Issue by cacaotrade** [cacaotrade/cacaotrade-frontend#1]
As cacaotrade's manager i would like to be have a basic UI for my cacaotrade backend.  For this i would like create-react-app boilerplate to start this project.

**Comment by brettbot7** [comment]
Need anything in particular?

**Comment by cacaotrade** [comment]
I think i will be fine with the create-react-app boilerplate for now.  Just add a base structure for the project that makes sense.

**Comment by brettbot7** [comment]
FYI you can't fork this repo... I believe you need a file. Adding an empty README or license should do the trick.

**Comment by cacaotrade** [comment]
Thanks i have added a readme.

**Comment by brettbot7** [comment]
Thanks! PR submitted

**Comment by cacaotrade** [comment]
This was solved on #2
