### ISSUE TITLE
Add basic layout for the project

### ISSUE THREAD

**Issue by cacaotrade** [cacaotrade/cacaotrade-frontend#3]
As a cacaotrade user i would like to be able to have a basic layout for the future developments of the frontend.  I would need the following to be done:

- [x] Have a nabvar with the pages Publications and Offers.
- [x] A link to a modal box to sign in and login/logout
- [x] The page Layout just needs a header with the page title(Publications, Offers, etc) a button to add a new one, and a table displaying mock data.
- [x] The form to add/edit a new Publication and Offer.

Would be nice if this is done using a library like react-material or react-bootstrap.

The backend project is https://github.com/cacaotrade/cacaotrade currently it is being developed,  you can take a look at the schemas that are on the models folder to mock the data for the tables.

**Comment by jhidalgoesp** [comment]
Solved on #8
